version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4597:4566-4597"
      - "8080:8080"
    environment:
      - SERVICES=
      - DEFAULT_REGION=eu-central-1
      - AWS_XRAY_SDK_ENABLED=true
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"